### ISSUE TITLE
Search for podcasts and episodes

### ISSUE THREAD

**Issue by probonopd** [Heckie75/kodi-addon-podcast#20]
This addon would be much more useful if one could use it to search for podcasts and episodes and to subscribe to them.

In other words, one should not need some other program to get to a lists of subscribed podcasts, but one should be able to do it using the addon itself.

**Comment by probonopd** [comment]
The [iTunes Search API](https://performance-partners.apple.com/search-api) is even documented.

**Comment by probonopd** [comment]
https://github.com/A600/plugin.video.itunes_podcasts seems to do it but it also seems to be broken.

**Comment by Heckie75** [comment]
@probonopd  As far as I understand this API can be used for promoting purposes only i.e. probably promoting Apple iTunes. Therefore this API doesn't work for KODI.

**Comment by probonopd** [comment]
Yes, there are several, but this one looks especially promising:

> gpodder.net is a libre web service that allows you to manage your podcast subscriptions and discover new content. If you use multiple devices, you can synchronize subscriptions and your listening progress.

* https://gpodder.net/
* https://gpoddernet.readthedocs.io/en/latest/api/
* Python client https://github.com/gpodder/mygpoclient

Thanks for looking into this.

**Comment by Heckie75** [comment]
@probonopd it seems that gpodder.net isn't very stable. All API requests result in a 500 internal server error. It seems to be a problem since 2021. 

I have looked around. There are other APIs like this one: https://api.podcastindex.org/

Unfortunately it is not very convenient because it requires registration and entering an API KEY and SECRET. What do you think?

**Comment by probonopd** [comment]
Indeed. Sorry I wasn't aware of this.

https://itunes.apple.com/search?term=...&entity=podcast doesn't seem to require an API key. 
On https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/index.html I can't see any restriction on using podcast URLs. Podcast URLs and metadata are not "Promo Content".

If Apple wanted to restrict the use of this API, I'd assume they would require an API key.

**Comment by Heckie75** [comment]
In v2.3.0 I've added a feature in order to search for podcasts in fyyd.de podcast directory
