### ISSUE TITLE
Feature request - icons

### ISSUE THREAD

**Issue by the-real-loondawg** [Heckie75/kodi-addon-podcast#26]
I hope this is the correct way to do this. I was hoping for a feature enhancement that would allow users to specify image files to use to identify each podcast. 

There are images associated with the individual episodes when retrieved. I was hoping to be able to specify an image for each podcast for the main view which right now only shows the generic RSS logo for each podcast listed. Like in the following picture it would be nice if each of those could be customized to improve the visual navigation.

![rss page](https://github.com/Heckie75/kodi-addon-podcast/assets/112091115/867d2aa1-2bbe-4a33-89da-a1f5969dcc2d)

Thank you.

**Comment by Heckie75** [comment]
Actually after the podcast has been loaded once, there shouldn't be the generic icon but the specific icon of the podcast. Therefore I don't understand what the requirement is?
