### ISSUE TITLE
HTTPStatusError Causes UnboundLocalError Exception

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#5]
This issue is somewhat related to #4, but it can be caused by any HTTP error, not only 403. The error code from the log is pasted below.
```
2021-05-13 19:58:14.235 T:11631   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'li' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 394, in <module>
                                                       mediathek.handle(sys.argv)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 381, in handle
                                                       self._render_rss(path, url)
                                                     File "/root/.kodi/addons/plugin.audio.podcasts/addon.py", line 338, in _render_rss
                                                       if "setDateTime" in dir(li):  # available since Kodi v20
                                                   UnboundLocalError: local variable 'li' referenced before assignment
                                                   -->End of Python script error report<--
```
If the HTTP request returns an error, then ```items``` has a length of 0. This means the ```for item in items:``` loop on line 331 will never execute, and as a result ```li``` will never be initialized. This causes the error on line 338 when ```li``` is referenced before being initialized.

I think that you are missing a couple of indents. The ```for item in items:``` loop on line 331 and the ```if "setDateTime" in dir(li):``` on line 338 should both be **inside** the ```if len(items) > 0:``` block on line 313. Those two blocks should only run if the length of ```items``` is greater than 0.

You could also consider using a ```try/except/else``` structure, where the ```else``` will only execute if the ```try``` was successful. I think that is a simpler solution that initializing an empty list for ```items```after an error and then using an if statement to only run if ```items``` is not empty. I changed the code to below and it fixed the issue.

```
        try:
            title, description, image, items = self._load_rss(url)
            if image:
                _update_Image(path, image)

        except HttpStatusError as error:
            xbmc.log("HTTP Status Error: %s, path=%s" %
                     (error.message, path), xbmc.LOGERROR)
            xbmcgui.Dialog().notification("HTTP Status Error", error.message)
            items = []
        else:
            if len(items) > 0:

                entry = {
                    "path": "latest",
                    "name": title,
                    "name2": description,
                    "icon": image,
                    "date": datetime.now(),
                    "specialsort": "top",
                    "type": items[0]["type"],
                    "params": [
                        {
                            "play_latest": url
                        }
                    ]
                }
                self._add_list_item(entry, path, playable=True)

            for item in items:
                li = self._create_list_item(item)
                xbmcplugin.addDirectoryItem(handle=self.addon_handle,
                                            listitem=li,
                                            url=item["stream_url"],
                                            isFolder=False)

            if "setDateTime" in dir(li):  # available since Kodi v20
                xbmcplugin.addSortMethod(
                    self.addon_handle, xbmcplugin.SORT_METHOD_DATE)
            xbmcplugin.endOfDirectory(self.addon_handle)
```

**Comment by Heckie75** [comment]
I changed it already locally. I am going to test it after another cup of coffee. 

Should I wait with pushing the PR for further findings?

**Comment by stobb3s** [comment]
It's a simple bug, so if it's working for you locally I think it's OK to push to the repo.

I have one other request, maybe for a future version. Since it's not a bug I won't open another issue for this. I noticed that you added a first entry in every feed which plays the most recent episode, and has the title of the podcast feed as the name. Personally, I do not like this. The first episode is the most recent for every podcast feed I subscribe to, so this is redundant and unnecessary. I have never seen a feature like this before in a podcast receiver. Perhaps you could add an option in the settings to disable this feature for users that do not want it? I see that if I comment out line 329, the entry goes away, so it should be easy to implement.

**Comment by Heckie75** [comment]
Ok, I'm going to push the bugfix soon. 

In terms of the first entry it is a personal _must-have_ requirement. I want to have an anchor for the most recent podcast in order to be able to bookmark it. Additionally I have a [timer addon](https://github.com/Heckie75/kodi-addon-heckies-timer) that I use to wake me up in the morning with the latest news. However, I can spend a setting for this later.

**Comment by Heckie75** [comment]
May be you like to test the latest version that I have pushed to my repository. There is also the new setting ;-)
Afterwards I would create the PR in the official repo.

**Comment by stobb3s** [comment]
I understand. I think making a setting would be good for a future released version. 

Also, I think the first entry having the same title as the podcast feed is confusing. At first, I thought it was a subdirectory. It's not clear for new users what it does. Maybe change it to a language-coded string such as "Most Recent Episode", "Newest Episode", or something similar?

**Comment by stobb3s** [comment]
Wow, so fast! I just downloaded the latest version and all of my podcasts are working now. And the new setting works great. I am going to close this issue and also #4. Thanks again for your support.

**Comment by Heckie75** [comment]
@stobb3s 

May be you have some time to take a look at the latest release. I have added support for importing OPML files and also gPodder subscriptions.

**Comment by stobb3s** [comment]
Yes, I am always happy to help you test new features. I have a few comments.

For the new import OPML file import feature, the file picker only accepts files with an .opml file extension, but many OPML files have an .xml extension. For example, OPML files exported by gPodder use .xml by default. Line 479 should be modified to allow both file extensions.

For the gpodder.net subscription downloads: 

1. I think that the 10 podcast feed limitation of the "group" option may be a problem for syncing gPodder.net if a person wants to import all of their subscriptions, since most people will have more than 10. Perhaps you could add another import option which will save the OPML text in the HTTP response directly to disk? So there would be both import to group and import to local OPML file.
2. "Select group for import" screen is not localized for English. It says gruppe instead of group. You have a hard-coded string on line 514. This is not allowed by the official repo rules.
3. For the language string files, there is a typo for string #32075. It should say "not" instead of "no" 
4. Consider adding a setting "Hostname" for the server URL. It would be pre-filled as "https://gpodder.net" by default, but allow the user to change the URL in case they want to use a private server instance. gPodder, AntennaPod, and other programs have this feature.

I did have some problems importing subscriptions gpodder.net, but it seems it is a problem with gpodder.net and not the add-on. The problem is that when you upload subscriptions to the server using the API (e.g. by gPodder or AntennaPod), the upload API only accepts a URL, but no ```title``` or ```text``` tag. gpodder.net then looks up the URL in the [Directory](https://gpodder.net/directory/). If the URL does not exist in the directory, then the title remains blank in the user's subscription file. gpodder.net does not attempt to parse the podcast title from the RSS file that the URL points to. I found [this issue](https://github.com/AntennaPod/AntennaPod/issues/771) which shows a similar problem with the gpodder.net database.

When I attempt to download the subscriptions to Kodi, the OPML response that the add-on receives has many items where only ```xmlUrl``` is filled, and ```title``` and ```text``` are blank. As a result, these items will be ignored by the add-on because ```title``` is blank. I logged the HTTP response and pasted it in an [attached file](https://github.com/Heckie75/kodi-addon-podcast/files/6498065/gpodder_http_response.txt) so you can see it. I used many random podcasts to test the feature, so these are quite obscure.

For me, this isn't an issue since I use local OPML files instead of gpodder.net to manage my subscriptions. But new users may upload their subscriptions from gPodder or AntennaPod to gpodder.net, attempt to download them to Kodi, and then be confused why some podcasts don't show up. Perhaps the add-on could be modified to recognize OPML with no ```title``` tag e.g. if no title exists, automatically create a title "Untitled Podcast [URL]", or something similar. Then the user could later change the title in the settings.

**Comment by Heckie75** [comment]
@stobb3s 

I have implemented all of it. Pls. double-check 2.0.3-pre2

Let's open a new issue if there are any findings.
