### ISSUE TITLE
Kodi Crashes When Attempting to Open Feed Ending In ".rss"

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#7]
As I mentioned in #5 , many of my gpodder.net podcasts are untitled. With the latest update, the add-on now saves them as "Untitled Podcast from [URL]", so they are showing up in the download. However, I noticed that several of these untitled feeds will crash Kodi if I try to open them. Debug log is [here](https://github.com/Heckie75/kodi-addon-podcast/files/6505797/kodi.log).

After some investigation, I found that only feeds with titles ending in ".rss" will crash Kodi. If I open the downloaded .opml file with a text editor and manually edit the title so that it no longer ends in .rss, then the podcast feed will open. I did some experimenting to see what other names will cause Kodi to crash, but I could not find anything:

- I tried putting a string ".rss" elsewhere in the title, but it only crashes when ".rss" is at the end
- I tried making titles ending in other common file extensions such as ".txt" ".mp3", ".jpg" etc., but only ".rss" will cause the crash

When I looked at the debug log, I found this line at the end:
```
2021-05-18 20:53:37.070 T:4252    DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.podcasts/opml-1/Untitled%20podcast%20from%20parkinson.libsyn.com...rss?rss=aHR0cHM6Ly9wYXJraW5zb24ubGlic3luLmNvbS9yc3M%3d)
```
Most likely the URL that is assigned to the directory cannot be parsed correctly by Kodi, and will cause it to crash. Maybe it is because "rss" is in the base URL and also the query string. I'm not sure if this is a bug in Kodi, or a bug in the add-on. To reproduce the issue, you may do the following:

1. Set [this OPML file](https://github.com/Heckie75/kodi-addon-podcast/files/6505860/stobb3s.s.Subscription.List.txt) to an OPML slot in Kodi. This was the OPML I downloaded with the new gpodder.net feature. Note: you will need to rename the file extension to .opml. I had to change it because GitHub won't accept .opml files for upload.
2. Attempt to open any feed that ends in ".rss"

**Comment by Heckie75** [comment]
@stobb3s 

Since the content of the plugin-URL is not really important I changed it so that it is just the index of the outline of the OPML File. You can find the change in v2.0.3-pre3

Thanks again for your effort!

**Comment by stobb3s** [comment]
Yes, it's fixed for me too. Thanks.
