### ISSUE TITLE
Login Settings for gpodder.net Do Not Change Immediately

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#8]
In the add-on settings menu, when the user changes the gpodder.net login settings (hostname/username/password), they do not go into effect immediately. To import some podcasts from gpodder.net after entering login info, you have to click "OK" on the right panel to close the add-on settings, then re-open the settings and click "Import..." You can't click "Import..." directly after changing the login settings.

I think this is not very intuitive. New users will enter their username and password, then immediately click "Import...", then they will receive a 404 response and be confused why it's not working and think the add-on is broken. You may want to consider moving this feature to the main menu of the plugin. e.g. have a ```listitem``` at the end of the main menu that says "Import feeds from gpodder.net", and open the import dialog from there. I think most plugins that have login features use the add-on settings only to enter the login info, and the login features are triggered when the plugin is run.

I have a few other comments:

1. For the "Import podcast list as OPML File" feature, the header of the file picker is wrong. In line 573: the string number should be 32080 instead of 32070.
2. In the "Assign OPML file" selection screen, it would be helpful to know which OPML slots are currently taken, so the user does not overwrite their settings by accident. In the import to group feature, it displays how many podcasts are open for each group to help the user choose. So maybe you could do something similar for import to OPML. Either display which OPML slots are currently taken, or don't display currently taken OPML slots in the list at all.
3.  There is no easy way to delete podcasts from groups. Currently, the only way is to enter the cursor in the text box and backspace both the URL and the title, but this is very cumbersome. Perhaps you could 1 delete button for each group which will open a list of podcasts feeds in the group to select which ones to delete.

**Comment by Heckie75** [comment]
@stobb3s 
Thanks again for your exelent feedback!

In terms of the gpodder credentials I have added an action in order to apply settings. It closes and reopens the settings dialog. I think that this is clear enough for new users. I don't want to keep the directory structure clean and focussed on content so that I don't want to add this functionallity there.

To your other comments:
1. Translation has been fixed 
2. The current filename is displayed now so that it is clearer that the slot is occupied and also what the content is
3. I have added an action in order to unassign OPML files

Since there are restrictions in terms of how the settings dialog in Kodi works I decided to close the settings dialog after performing OPML file actions. Otherwise the result of the action wouldn't be visible to the user. 

Nevertheless, I hope that these changes make it better for you.

**Comment by stobb3s** [comment]
> In terms of the gpodder credentials I have added an action in order to apply settings. It closes and reopens the settings dialog. I think that this is clear enough for new users. I don't want to keep the directory structure clean and focussed on content so that I don't want to add this functionallity there.

I agree. Putting the import feature in the main directory is not ideal for organization. I think your solution with the "Apply Changes" button is better.

>I have added an action in order to unassign OPML files

This is a nice feature, but in my original post I was referring a way to delete podcasts assigned to a group, not OPML files. This is what I had imagined as an example:

- You want to import 3 new podcasts to your Business group, but all podcasts are full in that group.
- You will have to delete 3 existing podcasts from the group to make room for the new ones. Currently this requires putting the cursor in the textboxes for URL and Title and backspacing all of the text out. This is very tedious and unpleasant for a living room/HTPC setup where Kodi is controlled with a TV remote.
- Instead, with the proposed new feature, there will be one "Delete Podcasts" button for each podcast group. When you click the button, it will open a ```xbmcgui.Dialog().multiselect()``` dialog which will allow you to select podcasts to delete from the group. After clicking OK, it will delete the selected podcasts from the group.

>PS: Maybe there should be a separate menu item in settings dialog where all actions are located?

I think this is a good idea. You could have a new menu item called "Actions". In the action menu, maybe include an ```lsep``` for the gpodder.net actions so it is clear that they are separate from the other. It would be more organized that way, and if you add more actions in a future release there would be an easy place to put them.

One other comment about the ```website``` tag in the addon.xml. You may not have noticed that [a wiki page](https://kodi.wiki/view/Add-on:RSS_Podcasts) was automatically generated for this add-on when it was merged into the official repo. I think you should change the ```website``` to the wiki URL. Most official add-ons use their wiki as the ```website```. You already have the GitHub URL for ```source``` anyway. After these new features are merged into the official repo, you may want to edit this wiki to instruct the users how to use the various features of the add-on. Most users will never view the GitHub Readme.md.

**Comment by Heckie75** [comment]
@stobb3s 
> This is a nice feature, but in my original post I was referring a way to delete podcasts assigned to a group

Ha ha, this was already available before. Tjhis can be done be deactivating the entry by using the toggle switch. I changed the label and hope that this is clearer now. Maybe something for the wiki - later. 

> Maybe there should be a separate menu item in settings dialog where all actions are located?

Now there is a new menu.

> One other comment about the website tag in the addon.xml.
Thanks for this hint. I will do it when this release is stable.
