### ISSUE TITLE
Requests Module Exceptions Not Handled

### ISSUE THREAD

**Issue by stobb3s** [Heckie75/kodi-addon-podcast#9]
If the requests module raises an exception, this is not handled by the add-on and will cause an error in Kodi. Currently, the add-on only checks the ```res.status_code``` to see if the request was successful, but there can be a failure for other reasons. For example, if the URL has a typo in it, there will be no server found and requests will raise a ```ConnectionError``` exception.

I think the requests calls in the ```_http_request``` method should be put in a ```try``` block, and there should be ```except``` blocks to handle the exceptions if there is an issue with the connection. Documentation of the exceptions that can be raised by the request modules can be found [here](https://docs.python-requests.org/en/latest/user/quickstart/#errors-and-exceptions). The add-on should have a dialog box or a Kodi notification to inform the user of the issue so they can fix it.

To reproduce the issue, you may do the following:

- Go to any URL in the settings, such as a podcast URL or the gpodder.net Hostname
- Add or delete a few characters in the base of the URL to purposely make a typo
- Perform a request to that modified URL

**Comment by Heckie75** [comment]
@stobb3s 

I improved error handling. 

see release 2.0.3-pre5

**Comment by stobb3s** [comment]
Thanks.
